// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

/**
 * Protobuf type {@code tutorial.ABookTruck}
 */
public final class ABookTruck extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.ABookTruck)
    ABookTruckOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ABookTruck.newBuilder() to construct.
  private ABookTruck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ABookTruck() {
    upsid_ = "";
    detail_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ABookTruck();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.class, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder.class);
  }

  private int bitField0_;
  public static final int PACKAGEID_FIELD_NUMBER = 1;
  private long packageid_ = 0L;
  /**
   * <code>required int64 packageid = 1;</code>
   * @return Whether the packageid field is set.
   */
  @java.lang.Override
  public boolean hasPackageid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 packageid = 1;</code>
   * @return The packageid.
   */
  @java.lang.Override
  public long getPackageid() {
    return packageid_;
  }

  public static final int WAREHOUSEID_FIELD_NUMBER = 2;
  private int warehouseid_ = 0;
  /**
   * <code>required int32 warehouseid = 2;</code>
   * @return Whether the warehouseid field is set.
   */
  @java.lang.Override
  public boolean hasWarehouseid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int32 warehouseid = 2;</code>
   * @return The warehouseid.
   */
  @java.lang.Override
  public int getWarehouseid() {
    return warehouseid_;
  }

  public static final int WAREHOUSEX_FIELD_NUMBER = 3;
  private int warehousex_ = 0;
  /**
   * <code>required int32 warehousex = 3;</code>
   * @return Whether the warehousex field is set.
   */
  @java.lang.Override
  public boolean hasWarehousex() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int32 warehousex = 3;</code>
   * @return The warehousex.
   */
  @java.lang.Override
  public int getWarehousex() {
    return warehousex_;
  }

  public static final int WAREHOUSEY_FIELD_NUMBER = 4;
  private int warehousey_ = 0;
  /**
   * <code>required int32 warehousey = 4;</code>
   * @return Whether the warehousey field is set.
   */
  @java.lang.Override
  public boolean hasWarehousey() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required int32 warehousey = 4;</code>
   * @return The warehousey.
   */
  @java.lang.Override
  public int getWarehousey() {
    return warehousey_;
  }

  public static final int DESTINATIONX_FIELD_NUMBER = 5;
  private int destinationx_ = 0;
  /**
   * <code>required int32 destinationx = 5;</code>
   * @return Whether the destinationx field is set.
   */
  @java.lang.Override
  public boolean hasDestinationx() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required int32 destinationx = 5;</code>
   * @return The destinationx.
   */
  @java.lang.Override
  public int getDestinationx() {
    return destinationx_;
  }

  public static final int DESTINATIONY_FIELD_NUMBER = 6;
  private int destinationy_ = 0;
  /**
   * <code>required int32 destinationy = 6;</code>
   * @return Whether the destinationy field is set.
   */
  @java.lang.Override
  public boolean hasDestinationy() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>required int32 destinationy = 6;</code>
   * @return The destinationy.
   */
  @java.lang.Override
  public int getDestinationy() {
    return destinationy_;
  }

  public static final int UPSID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object upsid_ = "";
  /**
   * <code>optional string upsid = 7;</code>
   * @return Whether the upsid field is set.
   */
  @java.lang.Override
  public boolean hasUpsid() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string upsid = 7;</code>
   * @return The upsid.
   */
  @java.lang.Override
  public java.lang.String getUpsid() {
    java.lang.Object ref = upsid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        upsid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string upsid = 7;</code>
   * @return The bytes for upsid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpsidBytes() {
    java.lang.Object ref = upsid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      upsid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQNUM_FIELD_NUMBER = 8;
  private long seqnum_ = 0L;
  /**
   * <code>optional int64 seqnum = 8;</code>
   * @return Whether the seqnum field is set.
   */
  @java.lang.Override
  public boolean hasSeqnum() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int64 seqnum = 8;</code>
   * @return The seqnum.
   */
  @java.lang.Override
  public long getSeqnum() {
    return seqnum_;
  }

  public static final int DETAIL_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object detail_ = "";
  /**
   * <code>optional string detail = 9;</code>
   * @return Whether the detail field is set.
   */
  @java.lang.Override
  public boolean hasDetail() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional string detail = 9;</code>
   * @return The detail.
   */
  @java.lang.Override
  public java.lang.String getDetail() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        detail_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string detail = 9;</code>
   * @return The bytes for detail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDetailBytes() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      detail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.ABookTruck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.ABookTruck)
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.class, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      packageid_ = 0L;
      warehouseid_ = 0;
      warehousex_ = 0;
      warehousey_ = 0;
      destinationx_ = 0;
      destinationy_ = 0;
      upsid_ = "";
      seqnum_ = 0L;
      detail_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck build() {
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck buildPartial() {
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck result = new edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.packageid_ = packageid_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.warehouseid_ = warehouseid_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.warehousex_ = warehousex_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.warehousey_ = warehousey_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.destinationx_ = destinationx_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.destinationy_ = destinationy_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.upsid_ = upsid_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.seqnum_ = seqnum_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.detail_ = detail_;
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private int bitField0_;

    private long packageid_ ;
    /**
     * <code>required int64 packageid = 1;</code>
     * @return Whether the packageid field is set.
     */
    @java.lang.Override
    public boolean hasPackageid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 packageid = 1;</code>
     * @return The packageid.
     */
    @java.lang.Override
    public long getPackageid() {
      return packageid_;
    }
    /**
     * <code>required int64 packageid = 1;</code>
     * @param value The packageid to set.
     * @return This builder for chaining.
     */
    public Builder setPackageid(long value) {

      packageid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 packageid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      packageid_ = 0L;
      onChanged();
      return this;
    }

    private int warehouseid_ ;
    /**
     * <code>required int32 warehouseid = 2;</code>
     * @return Whether the warehouseid field is set.
     */
    @java.lang.Override
    public boolean hasWarehouseid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 warehouseid = 2;</code>
     * @return The warehouseid.
     */
    @java.lang.Override
    public int getWarehouseid() {
      return warehouseid_;
    }
    /**
     * <code>required int32 warehouseid = 2;</code>
     * @param value The warehouseid to set.
     * @return This builder for chaining.
     */
    public Builder setWarehouseid(int value) {

      warehouseid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 warehouseid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarehouseid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      warehouseid_ = 0;
      onChanged();
      return this;
    }

    private int warehousex_ ;
    /**
     * <code>required int32 warehousex = 3;</code>
     * @return Whether the warehousex field is set.
     */
    @java.lang.Override
    public boolean hasWarehousex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 warehousex = 3;</code>
     * @return The warehousex.
     */
    @java.lang.Override
    public int getWarehousex() {
      return warehousex_;
    }
    /**
     * <code>required int32 warehousex = 3;</code>
     * @param value The warehousex to set.
     * @return This builder for chaining.
     */
    public Builder setWarehousex(int value) {

      warehousex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 warehousex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarehousex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      warehousex_ = 0;
      onChanged();
      return this;
    }

    private int warehousey_ ;
    /**
     * <code>required int32 warehousey = 4;</code>
     * @return Whether the warehousey field is set.
     */
    @java.lang.Override
    public boolean hasWarehousey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 warehousey = 4;</code>
     * @return The warehousey.
     */
    @java.lang.Override
    public int getWarehousey() {
      return warehousey_;
    }
    /**
     * <code>required int32 warehousey = 4;</code>
     * @param value The warehousey to set.
     * @return This builder for chaining.
     */
    public Builder setWarehousey(int value) {

      warehousey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 warehousey = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWarehousey() {
      bitField0_ = (bitField0_ & ~0x00000008);
      warehousey_ = 0;
      onChanged();
      return this;
    }

    private int destinationx_ ;
    /**
     * <code>required int32 destinationx = 5;</code>
     * @return Whether the destinationx field is set.
     */
    @java.lang.Override
    public boolean hasDestinationx() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 destinationx = 5;</code>
     * @return The destinationx.
     */
    @java.lang.Override
    public int getDestinationx() {
      return destinationx_;
    }
    /**
     * <code>required int32 destinationx = 5;</code>
     * @param value The destinationx to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationx(int value) {

      destinationx_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 destinationx = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationx() {
      bitField0_ = (bitField0_ & ~0x00000010);
      destinationx_ = 0;
      onChanged();
      return this;
    }

    private int destinationy_ ;
    /**
     * <code>required int32 destinationy = 6;</code>
     * @return Whether the destinationy field is set.
     */
    @java.lang.Override
    public boolean hasDestinationy() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 destinationy = 6;</code>
     * @return The destinationy.
     */
    @java.lang.Override
    public int getDestinationy() {
      return destinationy_;
    }
    /**
     * <code>required int32 destinationy = 6;</code>
     * @param value The destinationy to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationy(int value) {

      destinationy_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 destinationy = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationy() {
      bitField0_ = (bitField0_ & ~0x00000020);
      destinationy_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object upsid_ = "";
    /**
     * <code>optional string upsid = 7;</code>
     * @return Whether the upsid field is set.
     */
    public boolean hasUpsid() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string upsid = 7;</code>
     * @return The upsid.
     */
    public java.lang.String getUpsid() {
      java.lang.Object ref = upsid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          upsid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string upsid = 7;</code>
     * @return The bytes for upsid.
     */
    public com.google.protobuf.ByteString
        getUpsidBytes() {
      java.lang.Object ref = upsid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upsid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string upsid = 7;</code>
     * @param value The upsid to set.
     * @return This builder for chaining.
     */
    public Builder setUpsid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      upsid_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional string upsid = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpsid() {
      upsid_ = getDefaultInstance().getUpsid();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>optional string upsid = 7;</code>
     * @param value The bytes for upsid to set.
     * @return This builder for chaining.
     */
    public Builder setUpsidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      upsid_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private long seqnum_ ;
    /**
     * <code>optional int64 seqnum = 8;</code>
     * @return Whether the seqnum field is set.
     */
    @java.lang.Override
    public boolean hasSeqnum() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int64 seqnum = 8;</code>
     * @return The seqnum.
     */
    @java.lang.Override
    public long getSeqnum() {
      return seqnum_;
    }
    /**
     * <code>optional int64 seqnum = 8;</code>
     * @param value The seqnum to set.
     * @return This builder for chaining.
     */
    public Builder setSeqnum(long value) {

      seqnum_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 seqnum = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqnum() {
      bitField0_ = (bitField0_ & ~0x00000080);
      seqnum_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object detail_ = "";
    /**
     * <code>optional string detail = 9;</code>
     * @return Whether the detail field is set.
     */
    public boolean hasDetail() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string detail = 9;</code>
     * @return The detail.
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          detail_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string detail = 9;</code>
     * @return The bytes for detail.
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string detail = 9;</code>
     * @param value The detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      detail_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional string detail = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetail() {
      detail_ = getDefaultInstance().getDetail();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>optional string detail = 9;</code>
     * @param value The bytes for detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      detail_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.ABookTruck)
  }

  // @@protoc_insertion_point(class_scope:tutorial.ABookTruck)
  private static final edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck();
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ABookTruck>
      PARSER = new com.google.protobuf.AbstractParser<ABookTruck>() {
    @java.lang.Override
    public ABookTruck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ABookTruck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ABookTruck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

