// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

/**
 * Protobuf type {@code tutorial.AUCommunication}
 */
public final class AUCommunication extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.AUCommunication)
    AUCommunicationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AUCommunication.newBuilder() to construct.
  private AUCommunication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AUCommunication() {
    bookings_ = java.util.Collections.emptyList();
    delivers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AUCommunication();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_AUCommunication_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_AUCommunication_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication.class, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication.Builder.class);
  }

  private int bitField0_;
  public static final int BOOKINGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck> bookings_;
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck> getBookingsList() {
    return bookings_;
  }
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder> 
      getBookingsOrBuilderList() {
    return bookings_;
  }
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  @java.lang.Override
  public int getBookingsCount() {
    return bookings_.size();
  }
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getBookings(int index) {
    return bookings_.get(index);
  }
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder getBookingsOrBuilder(
      int index) {
    return bookings_.get(index);
  }

  public static final int DELIVERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver> delivers_;
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver> getDeliversList() {
    return delivers_;
  }
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder> 
      getDeliversOrBuilderList() {
    return delivers_;
  }
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  @java.lang.Override
  public int getDeliversCount() {
    return delivers_.size();
  }
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver getDelivers(int index) {
    return delivers_.get(index);
  }
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder getDeliversOrBuilder(
      int index) {
    return delivers_.get(index);
  }

  public static final int ACKS_FIELD_NUMBER = 3;
  private long acks_ = 0L;
  /**
   * <code>optional int64 acks = 3;</code>
   * @return Whether the acks field is set.
   */
  @java.lang.Override
  public boolean hasAcks() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 acks = 3;</code>
   * @return The acks.
   */
  @java.lang.Override
  public long getAcks() {
    return acks_;
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.AUCommunication}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.AUCommunication)
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunicationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_AUCommunication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_AUCommunication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication.class, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
      } else {
        bookings_ = null;
        bookingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (deliversBuilder_ == null) {
        delivers_ = java.util.Collections.emptyList();
      } else {
        delivers_ = null;
        deliversBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      acks_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_AUCommunication_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication build() {
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication buildPartial() {
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication result = new edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication result) {
      if (bookingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bookings_ = java.util.Collections.unmodifiableList(bookings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookings_ = bookings_;
      } else {
        result.bookings_ = bookingsBuilder_.build();
      }
      if (deliversBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          delivers_ = java.util.Collections.unmodifiableList(delivers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.delivers_ = delivers_;
      } else {
        result.delivers_ = deliversBuilder_.build();
      }
    }

    private void buildPartial0(edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.acks_ = acks_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private int bitField0_;

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck> bookings_ =
      java.util.Collections.emptyList();
    private void ensureBookingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bookings_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck>(bookings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder> bookingsBuilder_;

    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck> getBookingsList() {
      if (bookingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookings_);
      } else {
        return bookingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public int getBookingsCount() {
      if (bookingsBuilder_ == null) {
        return bookings_.size();
      } else {
        return bookingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getBookings(int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);
      } else {
        return bookingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder setBookings(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.set(index, value);
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder setBookings(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder addBookings(edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder addBookings(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(index, value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder addBookings(
        edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder addBookings(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder addAllBookings(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck> values) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookings_);
        onChanged();
      } else {
        bookingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder clearBookings() {
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public Builder removeBookings(int index) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.remove(index);
        onChanged();
      } else {
        bookingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder getBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder getBookingsOrBuilder(
        int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);  } else {
        return bookingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder> 
         getBookingsOrBuilderList() {
      if (bookingsBuilder_ != null) {
        return bookingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookings_);
      }
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder addBookingsBuilder() {
      return getBookingsFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder addBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder> 
         getBookingsBuilderList() {
      return getBookingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder> 
        getBookingsFieldBuilder() {
      if (bookingsBuilder_ == null) {
        bookingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder>(
                bookings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bookings_ = null;
      }
      return bookingsBuilder_;
    }

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver> delivers_ =
      java.util.Collections.emptyList();
    private void ensureDeliversIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        delivers_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver>(delivers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder> deliversBuilder_;

    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver> getDeliversList() {
      if (deliversBuilder_ == null) {
        return java.util.Collections.unmodifiableList(delivers_);
      } else {
        return deliversBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public int getDeliversCount() {
      if (deliversBuilder_ == null) {
        return delivers_.size();
      } else {
        return deliversBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver getDelivers(int index) {
      if (deliversBuilder_ == null) {
        return delivers_.get(index);
      } else {
        return deliversBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder setDelivers(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver value) {
      if (deliversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliversIsMutable();
        delivers_.set(index, value);
        onChanged();
      } else {
        deliversBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder setDelivers(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder builderForValue) {
      if (deliversBuilder_ == null) {
        ensureDeliversIsMutable();
        delivers_.set(index, builderForValue.build());
        onChanged();
      } else {
        deliversBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder addDelivers(edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver value) {
      if (deliversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliversIsMutable();
        delivers_.add(value);
        onChanged();
      } else {
        deliversBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder addDelivers(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver value) {
      if (deliversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliversIsMutable();
        delivers_.add(index, value);
        onChanged();
      } else {
        deliversBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder addDelivers(
        edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder builderForValue) {
      if (deliversBuilder_ == null) {
        ensureDeliversIsMutable();
        delivers_.add(builderForValue.build());
        onChanged();
      } else {
        deliversBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder addDelivers(
        int index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder builderForValue) {
      if (deliversBuilder_ == null) {
        ensureDeliversIsMutable();
        delivers_.add(index, builderForValue.build());
        onChanged();
      } else {
        deliversBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder addAllDelivers(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver> values) {
      if (deliversBuilder_ == null) {
        ensureDeliversIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, delivers_);
        onChanged();
      } else {
        deliversBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder clearDelivers() {
      if (deliversBuilder_ == null) {
        delivers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        deliversBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public Builder removeDelivers(int index) {
      if (deliversBuilder_ == null) {
        ensureDeliversIsMutable();
        delivers_.remove(index);
        onChanged();
      } else {
        deliversBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder getDeliversBuilder(
        int index) {
      return getDeliversFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder getDeliversOrBuilder(
        int index) {
      if (deliversBuilder_ == null) {
        return delivers_.get(index);  } else {
        return deliversBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder> 
         getDeliversOrBuilderList() {
      if (deliversBuilder_ != null) {
        return deliversBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(delivers_);
      }
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder addDeliversBuilder() {
      return getDeliversFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder addDeliversBuilder(
        int index) {
      return getDeliversFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder> 
         getDeliversBuilderList() {
      return getDeliversFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder> 
        getDeliversFieldBuilder() {
      if (deliversBuilder_ == null) {
        deliversBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver.Builder, edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder>(
                delivers_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        delivers_ = null;
      }
      return deliversBuilder_;
    }

    private long acks_ ;
    /**
     * <code>optional int64 acks = 3;</code>
     * @return Whether the acks field is set.
     */
    @java.lang.Override
    public boolean hasAcks() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 acks = 3;</code>
     * @return The acks.
     */
    @java.lang.Override
    public long getAcks() {
      return acks_;
    }
    /**
     * <code>optional int64 acks = 3;</code>
     * @param value The acks to set.
     * @return This builder for chaining.
     */
    public Builder setAcks(long value) {

      acks_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 acks = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcks() {
      bitField0_ = (bitField0_ & ~0x00000004);
      acks_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.AUCommunication)
  }

  // @@protoc_insertion_point(class_scope:tutorial.AUCommunication)
  private static final edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication();
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AUCommunication>
      PARSER = new com.google.protobuf.AbstractParser<AUCommunication>() {
    @java.lang.Override
    public AUCommunication parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AUCommunication> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AUCommunication> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.AUCommunication getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

