// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

public interface AUCommunicationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AUCommunication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck> 
      getBookingsList();
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getBookings(int index);
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  int getBookingsCount();
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder> 
      getBookingsOrBuilderList();
  /**
   * <code>repeated .tutorial.ABookTruck bookings = 1;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder getBookingsOrBuilder(
      int index);

  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver> 
      getDeliversList();
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliver getDelivers(int index);
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  int getDeliversCount();
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder> 
      getDeliversOrBuilderList();
  /**
   * <code>repeated .tutorial.AStartDeliver delivers = 2;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoAmazon.AStartDeliverOrBuilder getDeliversOrBuilder(
      int index);

  /**
   * <code>optional int64 acks = 3;</code>
   * @return Whether the acks field is set.
   */
  boolean hasAcks();
  /**
   * <code>optional int64 acks = 3;</code>
   * @return The acks.
   */
  long getAcks();
}
