// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

/**
 * <pre>
 * business logic commands : seq &amp; ack
 * </pre>
 *
 * Protobuf type {@code protocol.UGoPickup}
 */
public final class UGoPickup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.UGoPickup)
    UGoPickupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UGoPickup.newBuilder() to construct.
  private UGoPickup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UGoPickup() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UGoPickup();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UGoPickup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UGoPickup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.class, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder.class);
  }

  private int bitField0_;
  public static final int TRUCKID_FIELD_NUMBER = 1;
  private int truckid_ = 0;
  /**
   * <code>required int32 truckid = 1;</code>
   * @return Whether the truckid field is set.
   */
  @java.lang.Override
  public boolean hasTruckid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 truckid = 1;</code>
   * @return The truckid.
   */
  @java.lang.Override
  public int getTruckid() {
    return truckid_;
  }

  public static final int WHID_FIELD_NUMBER = 2;
  private int whid_ = 0;
  /**
   * <code>required int32 whid = 2;</code>
   * @return Whether the whid field is set.
   */
  @java.lang.Override
  public boolean hasWhid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required int32 whid = 2;</code>
   * @return The whid.
   */
  @java.lang.Override
  public int getWhid() {
    return whid_;
  }

  public static final int SEQNUM_FIELD_NUMBER = 3;
  private long seqnum_ = 0L;
  /**
   * <code>required int64 seqnum = 3;</code>
   * @return Whether the seqnum field is set.
   */
  @java.lang.Override
  public boolean hasSeqnum() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required int64 seqnum = 3;</code>
   * @return The seqnum.
   */
  @java.lang.Override
  public long getSeqnum() {
    return seqnum_;
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * business logic commands : seq &amp; ack
   * </pre>
   *
   * Protobuf type {@code protocol.UGoPickup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.UGoPickup)
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UGoPickup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UGoPickup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.class, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      truckid_ = 0;
      whid_ = 0;
      seqnum_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UGoPickup_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup build() {
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup buildPartial() {
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup result = new edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.truckid_ = truckid_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.whid_ = whid_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.seqnum_ = seqnum_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private int bitField0_;

    private int truckid_ ;
    /**
     * <code>required int32 truckid = 1;</code>
     * @return Whether the truckid field is set.
     */
    @java.lang.Override
    public boolean hasTruckid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 truckid = 1;</code>
     * @return The truckid.
     */
    @java.lang.Override
    public int getTruckid() {
      return truckid_;
    }
    /**
     * <code>required int32 truckid = 1;</code>
     * @param value The truckid to set.
     * @return This builder for chaining.
     */
    public Builder setTruckid(int value) {

      truckid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 truckid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTruckid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      truckid_ = 0;
      onChanged();
      return this;
    }

    private int whid_ ;
    /**
     * <code>required int32 whid = 2;</code>
     * @return Whether the whid field is set.
     */
    @java.lang.Override
    public boolean hasWhid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 whid = 2;</code>
     * @return The whid.
     */
    @java.lang.Override
    public int getWhid() {
      return whid_;
    }
    /**
     * <code>required int32 whid = 2;</code>
     * @param value The whid to set.
     * @return This builder for chaining.
     */
    public Builder setWhid(int value) {

      whid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 whid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      whid_ = 0;
      onChanged();
      return this;
    }

    private long seqnum_ ;
    /**
     * <code>required int64 seqnum = 3;</code>
     * @return Whether the seqnum field is set.
     */
    @java.lang.Override
    public boolean hasSeqnum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 seqnum = 3;</code>
     * @return The seqnum.
     */
    @java.lang.Override
    public long getSeqnum() {
      return seqnum_;
    }
    /**
     * <code>required int64 seqnum = 3;</code>
     * @param value The seqnum to set.
     * @return This builder for chaining.
     */
    public Builder setSeqnum(long value) {

      seqnum_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 seqnum = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqnum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      seqnum_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.UGoPickup)
  }

  // @@protoc_insertion_point(class_scope:protocol.UGoPickup)
  private static final edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup();
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<UGoPickup>
      PARSER = new com.google.protobuf.AbstractParser<UGoPickup>() {
    @java.lang.Override
    public UGoPickup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UGoPickup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UGoPickup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

