// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public interface UResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UResponses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished> 
      getCompletionsList();
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished getCompletions(int index);
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  int getCompletionsCount();
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder> 
      getCompletionsOrBuilderList();
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder getCompletionsOrBuilder(
      int index);

  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade> 
      getDeliveredList();
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade getDelivered(int index);
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  int getDeliveredCount();
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder> 
      getDeliveredOrBuilderList();
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder getDeliveredOrBuilder(
      int index);

  /**
   * <code>optional bool finished = 3;</code>
   * @return Whether the finished field is set.
   */
  boolean hasFinished();
  /**
   * <code>optional bool finished = 3;</code>
   * @return The finished.
   */
  boolean getFinished();

  /**
   * <code>repeated int64 acks = 4;</code>
   * @return A list containing the acks.
   */
  java.util.List<java.lang.Long> getAcksList();
  /**
   * <code>repeated int64 acks = 4;</code>
   * @return The count of acks.
   */
  int getAcksCount();
  /**
   * <code>repeated int64 acks = 4;</code>
   * @param index The index of the element to return.
   * @return The acks at the given index.
   */
  long getAcks(int index);

  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck> 
      getTruckstatusList();
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck getTruckstatus(int index);
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  int getTruckstatusCount();
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder> 
      getTruckstatusOrBuilderList();
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder getTruckstatusOrBuilder(
      int index);

  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr> 
      getErrorList();
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr getError(int index);
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  int getErrorCount();
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder> 
      getErrorOrBuilderList();
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder getErrorOrBuilder(
      int index);
}
