// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

/**
 * Protobuf type {@code protocol.UResponses}
 */
public final class UResponses extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.UResponses)
    UResponsesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UResponses.newBuilder() to construct.
  private UResponses(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UResponses() {
    completions_ = java.util.Collections.emptyList();
    delivered_ = java.util.Collections.emptyList();
    acks_ = emptyLongList();
    truckstatus_ = java.util.Collections.emptyList();
    error_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UResponses();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UResponses_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UResponses_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses.class, edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses.Builder.class);
  }

  private int bitField0_;
  public static final int COMPLETIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished> completions_;
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished> getCompletionsList() {
    return completions_;
  }
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder> 
      getCompletionsOrBuilderList() {
    return completions_;
  }
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  @java.lang.Override
  public int getCompletionsCount() {
    return completions_.size();
  }
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished getCompletions(int index) {
    return completions_.get(index);
  }
  /**
   * <code>repeated .protocol.UFinished completions = 1;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder getCompletionsOrBuilder(
      int index) {
    return completions_.get(index);
  }

  public static final int DELIVERED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade> delivered_;
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade> getDeliveredList() {
    return delivered_;
  }
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder> 
      getDeliveredOrBuilderList() {
    return delivered_;
  }
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  @java.lang.Override
  public int getDeliveredCount() {
    return delivered_.size();
  }
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade getDelivered(int index) {
    return delivered_.get(index);
  }
  /**
   * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder getDeliveredOrBuilder(
      int index) {
    return delivered_.get(index);
  }

  public static final int FINISHED_FIELD_NUMBER = 3;
  private boolean finished_ = false;
  /**
   * <code>optional bool finished = 3;</code>
   * @return Whether the finished field is set.
   */
  @java.lang.Override
  public boolean hasFinished() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool finished = 3;</code>
   * @return The finished.
   */
  @java.lang.Override
  public boolean getFinished() {
    return finished_;
  }

  public static final int ACKS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList acks_;
  /**
   * <code>repeated int64 acks = 4;</code>
   * @return A list containing the acks.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getAcksList() {
    return acks_;
  }
  /**
   * <code>repeated int64 acks = 4;</code>
   * @return The count of acks.
   */
  public int getAcksCount() {
    return acks_.size();
  }
  /**
   * <code>repeated int64 acks = 4;</code>
   * @param index The index of the element to return.
   * @return The acks at the given index.
   */
  public long getAcks(int index) {
    return acks_.getLong(index);
  }

  public static final int TRUCKSTATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck> truckstatus_;
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck> getTruckstatusList() {
    return truckstatus_;
  }
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder> 
      getTruckstatusOrBuilderList() {
    return truckstatus_;
  }
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  @java.lang.Override
  public int getTruckstatusCount() {
    return truckstatus_.size();
  }
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck getTruckstatus(int index) {
    return truckstatus_.get(index);
  }
  /**
   * <code>repeated .protocol.UTruck truckstatus = 5;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder getTruckstatusOrBuilder(
      int index) {
    return truckstatus_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr> error_;
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  @java.lang.Override
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr> getErrorList() {
    return error_;
  }
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder> 
      getErrorOrBuilderList() {
    return error_;
  }
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  @java.lang.Override
  public int getErrorCount() {
    return error_.size();
  }
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr getError(int index) {
    return error_.get(index);
  }
  /**
   * <code>repeated .protocol.UErr error = 6;</code>
   */
  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder getErrorOrBuilder(
      int index) {
    return error_.get(index);
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.UResponses}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.UResponses)
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponsesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UResponses_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UResponses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses.class, edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (completionsBuilder_ == null) {
        completions_ = java.util.Collections.emptyList();
      } else {
        completions_ = null;
        completionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (deliveredBuilder_ == null) {
        delivered_ = java.util.Collections.emptyList();
      } else {
        delivered_ = null;
        deliveredBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      finished_ = false;
      acks_ = emptyLongList();
      if (truckstatusBuilder_ == null) {
        truckstatus_ = java.util.Collections.emptyList();
      } else {
        truckstatus_ = null;
        truckstatusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (errorBuilder_ == null) {
        error_ = java.util.Collections.emptyList();
      } else {
        error_ = null;
        errorBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UResponses_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses build() {
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses buildPartial() {
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses result = new edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses result) {
      if (completionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          completions_ = java.util.Collections.unmodifiableList(completions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.completions_ = completions_;
      } else {
        result.completions_ = completionsBuilder_.build();
      }
      if (deliveredBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          delivered_ = java.util.Collections.unmodifiableList(delivered_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.delivered_ = delivered_;
      } else {
        result.delivered_ = deliveredBuilder_.build();
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        acks_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.acks_ = acks_;
      if (truckstatusBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          truckstatus_ = java.util.Collections.unmodifiableList(truckstatus_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.truckstatus_ = truckstatus_;
      } else {
        result.truckstatus_ = truckstatusBuilder_.build();
      }
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          error_ = java.util.Collections.unmodifiableList(error_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
    }

    private void buildPartial0(edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.finished_ = finished_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private int bitField0_;

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished> completions_ =
      java.util.Collections.emptyList();
    private void ensureCompletionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        completions_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished>(completions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder> completionsBuilder_;

    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished> getCompletionsList() {
      if (completionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(completions_);
      } else {
        return completionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public int getCompletionsCount() {
      if (completionsBuilder_ == null) {
        return completions_.size();
      } else {
        return completionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished getCompletions(int index) {
      if (completionsBuilder_ == null) {
        return completions_.get(index);
      } else {
        return completionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder setCompletions(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished value) {
      if (completionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompletionsIsMutable();
        completions_.set(index, value);
        onChanged();
      } else {
        completionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder setCompletions(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder builderForValue) {
      if (completionsBuilder_ == null) {
        ensureCompletionsIsMutable();
        completions_.set(index, builderForValue.build());
        onChanged();
      } else {
        completionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder addCompletions(edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished value) {
      if (completionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompletionsIsMutable();
        completions_.add(value);
        onChanged();
      } else {
        completionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder addCompletions(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished value) {
      if (completionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompletionsIsMutable();
        completions_.add(index, value);
        onChanged();
      } else {
        completionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder addCompletions(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder builderForValue) {
      if (completionsBuilder_ == null) {
        ensureCompletionsIsMutable();
        completions_.add(builderForValue.build());
        onChanged();
      } else {
        completionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder addCompletions(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder builderForValue) {
      if (completionsBuilder_ == null) {
        ensureCompletionsIsMutable();
        completions_.add(index, builderForValue.build());
        onChanged();
      } else {
        completionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder addAllCompletions(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished> values) {
      if (completionsBuilder_ == null) {
        ensureCompletionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, completions_);
        onChanged();
      } else {
        completionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder clearCompletions() {
      if (completionsBuilder_ == null) {
        completions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        completionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public Builder removeCompletions(int index) {
      if (completionsBuilder_ == null) {
        ensureCompletionsIsMutable();
        completions_.remove(index);
        onChanged();
      } else {
        completionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder getCompletionsBuilder(
        int index) {
      return getCompletionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder getCompletionsOrBuilder(
        int index) {
      if (completionsBuilder_ == null) {
        return completions_.get(index);  } else {
        return completionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder> 
         getCompletionsOrBuilderList() {
      if (completionsBuilder_ != null) {
        return completionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(completions_);
      }
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder addCompletionsBuilder() {
      return getCompletionsFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder addCompletionsBuilder(
        int index) {
      return getCompletionsFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UFinished completions = 1;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder> 
         getCompletionsBuilderList() {
      return getCompletionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder> 
        getCompletionsFieldBuilder() {
      if (completionsBuilder_ == null) {
        completionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinished.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UFinishedOrBuilder>(
                completions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        completions_ = null;
      }
      return completionsBuilder_;
    }

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade> delivered_ =
      java.util.Collections.emptyList();
    private void ensureDeliveredIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        delivered_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade>(delivered_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder> deliveredBuilder_;

    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade> getDeliveredList() {
      if (deliveredBuilder_ == null) {
        return java.util.Collections.unmodifiableList(delivered_);
      } else {
        return deliveredBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public int getDeliveredCount() {
      if (deliveredBuilder_ == null) {
        return delivered_.size();
      } else {
        return deliveredBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade getDelivered(int index) {
      if (deliveredBuilder_ == null) {
        return delivered_.get(index);
      } else {
        return deliveredBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder setDelivered(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade value) {
      if (deliveredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliveredIsMutable();
        delivered_.set(index, value);
        onChanged();
      } else {
        deliveredBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder setDelivered(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder builderForValue) {
      if (deliveredBuilder_ == null) {
        ensureDeliveredIsMutable();
        delivered_.set(index, builderForValue.build());
        onChanged();
      } else {
        deliveredBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder addDelivered(edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade value) {
      if (deliveredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliveredIsMutable();
        delivered_.add(value);
        onChanged();
      } else {
        deliveredBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder addDelivered(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade value) {
      if (deliveredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliveredIsMutable();
        delivered_.add(index, value);
        onChanged();
      } else {
        deliveredBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder addDelivered(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder builderForValue) {
      if (deliveredBuilder_ == null) {
        ensureDeliveredIsMutable();
        delivered_.add(builderForValue.build());
        onChanged();
      } else {
        deliveredBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder addDelivered(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder builderForValue) {
      if (deliveredBuilder_ == null) {
        ensureDeliveredIsMutable();
        delivered_.add(index, builderForValue.build());
        onChanged();
      } else {
        deliveredBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder addAllDelivered(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade> values) {
      if (deliveredBuilder_ == null) {
        ensureDeliveredIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, delivered_);
        onChanged();
      } else {
        deliveredBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder clearDelivered() {
      if (deliveredBuilder_ == null) {
        delivered_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        deliveredBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public Builder removeDelivered(int index) {
      if (deliveredBuilder_ == null) {
        ensureDeliveredIsMutable();
        delivered_.remove(index);
        onChanged();
      } else {
        deliveredBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder getDeliveredBuilder(
        int index) {
      return getDeliveredFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder getDeliveredOrBuilder(
        int index) {
      if (deliveredBuilder_ == null) {
        return delivered_.get(index);  } else {
        return deliveredBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder> 
         getDeliveredOrBuilderList() {
      if (deliveredBuilder_ != null) {
        return deliveredBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(delivered_);
      }
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder addDeliveredBuilder() {
      return getDeliveredFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder addDeliveredBuilder(
        int index) {
      return getDeliveredFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UDeliveryMade delivered = 2;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder> 
         getDeliveredBuilderList() {
      return getDeliveredFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder> 
        getDeliveredFieldBuilder() {
      if (deliveredBuilder_ == null) {
        deliveredBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMade.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UDeliveryMadeOrBuilder>(
                delivered_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        delivered_ = null;
      }
      return deliveredBuilder_;
    }

    private boolean finished_ ;
    /**
     * <code>optional bool finished = 3;</code>
     * @return Whether the finished field is set.
     */
    @java.lang.Override
    public boolean hasFinished() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool finished = 3;</code>
     * @return The finished.
     */
    @java.lang.Override
    public boolean getFinished() {
      return finished_;
    }
    /**
     * <code>optional bool finished = 3;</code>
     * @param value The finished to set.
     * @return This builder for chaining.
     */
    public Builder setFinished(boolean value) {

      finished_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool finished = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinished() {
      bitField0_ = (bitField0_ & ~0x00000004);
      finished_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList acks_ = emptyLongList();
    private void ensureAcksIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        acks_ = mutableCopy(acks_);
        bitField0_ |= 0x00000008;
      }
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @return A list containing the acks.
     */
    public java.util.List<java.lang.Long>
        getAcksList() {
      return ((bitField0_ & 0x00000008) != 0) ?
               java.util.Collections.unmodifiableList(acks_) : acks_;
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @return The count of acks.
     */
    public int getAcksCount() {
      return acks_.size();
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @param index The index of the element to return.
     * @return The acks at the given index.
     */
    public long getAcks(int index) {
      return acks_.getLong(index);
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @param index The index to set the value at.
     * @param value The acks to set.
     * @return This builder for chaining.
     */
    public Builder setAcks(
        int index, long value) {

      ensureAcksIsMutable();
      acks_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @param value The acks to add.
     * @return This builder for chaining.
     */
    public Builder addAcks(long value) {

      ensureAcksIsMutable();
      acks_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @param values The acks to add.
     * @return This builder for chaining.
     */
    public Builder addAllAcks(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAcksIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, acks_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcks() {
      acks_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck> truckstatus_ =
      java.util.Collections.emptyList();
    private void ensureTruckstatusIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        truckstatus_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck>(truckstatus_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder> truckstatusBuilder_;

    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck> getTruckstatusList() {
      if (truckstatusBuilder_ == null) {
        return java.util.Collections.unmodifiableList(truckstatus_);
      } else {
        return truckstatusBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public int getTruckstatusCount() {
      if (truckstatusBuilder_ == null) {
        return truckstatus_.size();
      } else {
        return truckstatusBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck getTruckstatus(int index) {
      if (truckstatusBuilder_ == null) {
        return truckstatus_.get(index);
      } else {
        return truckstatusBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder setTruckstatus(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck value) {
      if (truckstatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTruckstatusIsMutable();
        truckstatus_.set(index, value);
        onChanged();
      } else {
        truckstatusBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder setTruckstatus(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder builderForValue) {
      if (truckstatusBuilder_ == null) {
        ensureTruckstatusIsMutable();
        truckstatus_.set(index, builderForValue.build());
        onChanged();
      } else {
        truckstatusBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder addTruckstatus(edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck value) {
      if (truckstatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTruckstatusIsMutable();
        truckstatus_.add(value);
        onChanged();
      } else {
        truckstatusBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder addTruckstatus(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck value) {
      if (truckstatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTruckstatusIsMutable();
        truckstatus_.add(index, value);
        onChanged();
      } else {
        truckstatusBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder addTruckstatus(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder builderForValue) {
      if (truckstatusBuilder_ == null) {
        ensureTruckstatusIsMutable();
        truckstatus_.add(builderForValue.build());
        onChanged();
      } else {
        truckstatusBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder addTruckstatus(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder builderForValue) {
      if (truckstatusBuilder_ == null) {
        ensureTruckstatusIsMutable();
        truckstatus_.add(index, builderForValue.build());
        onChanged();
      } else {
        truckstatusBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder addAllTruckstatus(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck> values) {
      if (truckstatusBuilder_ == null) {
        ensureTruckstatusIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, truckstatus_);
        onChanged();
      } else {
        truckstatusBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder clearTruckstatus() {
      if (truckstatusBuilder_ == null) {
        truckstatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        truckstatusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public Builder removeTruckstatus(int index) {
      if (truckstatusBuilder_ == null) {
        ensureTruckstatusIsMutable();
        truckstatus_.remove(index);
        onChanged();
      } else {
        truckstatusBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder getTruckstatusBuilder(
        int index) {
      return getTruckstatusFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder getTruckstatusOrBuilder(
        int index) {
      if (truckstatusBuilder_ == null) {
        return truckstatus_.get(index);  } else {
        return truckstatusBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder> 
         getTruckstatusOrBuilderList() {
      if (truckstatusBuilder_ != null) {
        return truckstatusBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(truckstatus_);
      }
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder addTruckstatusBuilder() {
      return getTruckstatusFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder addTruckstatusBuilder(
        int index) {
      return getTruckstatusFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UTruck truckstatus = 5;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder> 
         getTruckstatusBuilderList() {
      return getTruckstatusFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder> 
        getTruckstatusFieldBuilder() {
      if (truckstatusBuilder_ == null) {
        truckstatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruck.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UTruckOrBuilder>(
                truckstatus_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        truckstatus_ = null;
      }
      return truckstatusBuilder_;
    }

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr> error_ =
      java.util.Collections.emptyList();
    private void ensureErrorIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        error_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr>(error_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder> errorBuilder_;

    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr> getErrorList() {
      if (errorBuilder_ == null) {
        return java.util.Collections.unmodifiableList(error_);
      } else {
        return errorBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public int getErrorCount() {
      if (errorBuilder_ == null) {
        return error_.size();
      } else {
        return errorBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr getError(int index) {
      if (errorBuilder_ == null) {
        return error_.get(index);
      } else {
        return errorBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder setError(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorIsMutable();
        error_.set(index, value);
        onChanged();
      } else {
        errorBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder setError(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder builderForValue) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.set(index, builderForValue.build());
        onChanged();
      } else {
        errorBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder addError(edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorIsMutable();
        error_.add(value);
        onChanged();
      } else {
        errorBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder addError(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorIsMutable();
        error_.add(index, value);
        onChanged();
      } else {
        errorBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder addError(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder builderForValue) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.add(builderForValue.build());
        onChanged();
      } else {
        errorBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder addError(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder builderForValue) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.add(index, builderForValue.build());
        onChanged();
      } else {
        errorBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder addAllError(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr> values) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, error_);
        onChanged();
      } else {
        errorBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public Builder removeError(int index) {
      if (errorBuilder_ == null) {
        ensureErrorIsMutable();
        error_.remove(index);
        onChanged();
      } else {
        errorBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder getErrorBuilder(
        int index) {
      return getErrorFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder getErrorOrBuilder(
        int index) {
      if (errorBuilder_ == null) {
        return error_.get(index);  } else {
        return errorBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder> 
         getErrorOrBuilderList() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(error_);
      }
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder addErrorBuilder() {
      return getErrorFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder addErrorBuilder(
        int index) {
      return getErrorFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UErr error = 6;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder> 
         getErrorBuilderList() {
      return getErrorFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErr.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UErrOrBuilder>(
                error_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.UResponses)
  }

  // @@protoc_insertion_point(class_scope:protocol.UResponses)
  private static final edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses();
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<UResponses>
      PARSER = new com.google.protobuf.AbstractParser<UResponses>() {
    @java.lang.Override
    public UResponses parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UResponses> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UResponses> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UResponses getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

