// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public final class WorldUps {
  private WorldUps() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UInitTruck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UInitTruck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UConnect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UConnect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UConnected_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UConnected_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UGoPickup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UGoPickup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UFinished_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UFinished_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UDeliveryMade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UDeliveryMade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UDeliveryLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UDeliveryLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UGoDeliver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UGoDeliver_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UErr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UErr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UTruck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UTruck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UCommands_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UCommands_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UResponses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017world_ups.proto\022\010protocol\".\n\nUInitTruc" +
      "k\022\n\n\002id\030\001 \002(\005\022\t\n\001x\030\002 \002(\005\022\t\n\001y\030\003 \002(\005\"S\n\010U" +
      "Connect\022\017\n\007worldid\030\001 \001(\003\022$\n\006trucks\030\002 \003(\013" +
      "2\024.protocol.UInitTruck\022\020\n\010isAmazon\030\003 \002(\010" +
      "\"-\n\nUConnected\022\017\n\007worldid\030\001 \002(\003\022\016\n\006resul" +
      "t\030\002 \002(\t\":\n\tUGoPickup\022\017\n\007truckid\030\001 \002(\005\022\014\n" +
      "\004whid\030\002 \002(\005\022\016\n\006seqnum\030\003 \002(\003\"R\n\tUFinished" +
      "\022\017\n\007truckid\030\001 \002(\005\022\t\n\001x\030\002 \002(\005\022\t\n\001y\030\003 \002(\005\022" +
      "\016\n\006status\030\004 \002(\t\022\016\n\006seqnum\030\005 \002(\003\"C\n\rUDeli" +
      "veryMade\022\017\n\007truckid\030\001 \002(\005\022\021\n\tpackageid\030\002" +
      " \002(\003\022\016\n\006seqnum\030\003 \002(\003\"<\n\021UDeliveryLocatio" +
      "n\022\021\n\tpackageid\030\001 \002(\003\022\t\n\001x\030\002 \002(\005\022\t\n\001y\030\003 \002" +
      "(\005\"\\\n\nUGoDeliver\022\017\n\007truckid\030\001 \002(\005\022-\n\010pac" +
      "kages\030\002 \003(\0132\033.protocol.UDeliveryLocation" +
      "\022\016\n\006seqnum\030\003 \002(\003\"9\n\004UErr\022\013\n\003err\030\001 \002(\t\022\024\n" +
      "\014originseqnum\030\002 \002(\003\022\016\n\006seqnum\030\003 \002(\003\")\n\006U" +
      "Query\022\017\n\007truckid\030\001 \002(\005\022\016\n\006seqnum\030\002 \002(\003\"O" +
      "\n\006UTruck\022\017\n\007truckid\030\001 \002(\005\022\016\n\006status\030\002 \002(" +
      "\t\022\t\n\001x\030\003 \002(\005\022\t\n\001y\030\004 \002(\005\022\016\n\006seqnum\030\005 \002(\003\"" +
      "\262\001\n\tUCommands\022$\n\007pickups\030\001 \003(\0132\023.protoco" +
      "l.UGoPickup\022(\n\ndeliveries\030\002 \003(\0132\024.protoc" +
      "ol.UGoDeliver\022\020\n\010simspeed\030\003 \001(\r\022\022\n\ndisco" +
      "nnect\030\004 \001(\010\022!\n\007queries\030\005 \003(\0132\020.protocol." +
      "UQuery\022\014\n\004acks\030\006 \003(\003\"\310\001\n\nUResponses\022(\n\013c" +
      "ompletions\030\001 \003(\0132\023.protocol.UFinished\022*\n" +
      "\tdelivered\030\002 \003(\0132\027.protocol.UDeliveryMad" +
      "e\022\020\n\010finished\030\003 \001(\010\022\014\n\004acks\030\004 \003(\003\022%\n\013tru" +
      "ckstatus\030\005 \003(\0132\020.protocol.UTruck\022\035\n\005erro" +
      "r\030\006 \003(\0132\016.protocol.UErrB0\n*edu.duke.ece5" +
      "68.minUPS.protocol.UPStoWorldH\002P\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_UInitTruck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_UInitTruck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UInitTruck_descriptor,
        new java.lang.String[] { "Id", "X", "Y", });
    internal_static_protocol_UConnect_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_UConnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UConnect_descriptor,
        new java.lang.String[] { "Worldid", "Trucks", "IsAmazon", });
    internal_static_protocol_UConnected_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_UConnected_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UConnected_descriptor,
        new java.lang.String[] { "Worldid", "Result", });
    internal_static_protocol_UGoPickup_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_UGoPickup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UGoPickup_descriptor,
        new java.lang.String[] { "Truckid", "Whid", "Seqnum", });
    internal_static_protocol_UFinished_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_UFinished_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UFinished_descriptor,
        new java.lang.String[] { "Truckid", "X", "Y", "Status", "Seqnum", });
    internal_static_protocol_UDeliveryMade_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protocol_UDeliveryMade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UDeliveryMade_descriptor,
        new java.lang.String[] { "Truckid", "Packageid", "Seqnum", });
    internal_static_protocol_UDeliveryLocation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protocol_UDeliveryLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UDeliveryLocation_descriptor,
        new java.lang.String[] { "Packageid", "X", "Y", });
    internal_static_protocol_UGoDeliver_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protocol_UGoDeliver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UGoDeliver_descriptor,
        new java.lang.String[] { "Truckid", "Packages", "Seqnum", });
    internal_static_protocol_UErr_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_protocol_UErr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UErr_descriptor,
        new java.lang.String[] { "Err", "Originseqnum", "Seqnum", });
    internal_static_protocol_UQuery_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_protocol_UQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UQuery_descriptor,
        new java.lang.String[] { "Truckid", "Seqnum", });
    internal_static_protocol_UTruck_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_protocol_UTruck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UTruck_descriptor,
        new java.lang.String[] { "Truckid", "Status", "X", "Y", "Seqnum", });
    internal_static_protocol_UCommands_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_protocol_UCommands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UCommands_descriptor,
        new java.lang.String[] { "Pickups", "Deliveries", "Simspeed", "Disconnect", "Queries", "Acks", });
    internal_static_protocol_UResponses_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_protocol_UResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UResponses_descriptor,
        new java.lang.String[] { "Completions", "Delivered", "Finished", "Acks", "Truckstatus", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
