version: "3"

services:
  db:
    image: postgres:12-alpine3.15
    environment:
      POSTGRES_DB: upsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    restart: always

  ups:
    build: minUPS
    ports:
      - "45678:45678"
      - "22222:22222"
    depends_on:
      - db